### ISSUE TITLE
Update gradle task names, leave behind old names as undocumented aliases for now

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-gradle-plugin#20]
"warn" and "fix" are legacy names from when we thought quite a bit differently about the intended usage of these things. 

"rewriteFix" should be renamed to "rewriteRun". 
"rewriteWarn" should be renamed to "rewriteDryRun". The existing behavior only prints which files would be changed by which visitors, which isn't very useful. It should instead print what the actual changes would be, similar to what `git diff` would show you after running rewriteRun/rewriteFix

**Comment by aegershman** [comment]
moved changing rewriteDryRun's behavior to a separate issue https://github.com/openrewrite/rewrite-gradle-plugin/issues/27

**Comment by okundzich** [comment]
Why are we leaving undocumented aliases for now? And at what point do we want to remove them?

Also, rewriteDryRun could produce a very long diff if it produces full output rather than a list of files changed. git diff paginates it, but build plugins do not. Maybe leaving existing behaviour is better.

**Comment by aegershman** [comment]
I will change the title for this and edit the original issue body-- we aren't leaving undocumented aliases any longer, the names are fully changed.

As for changes in rewriteDryRun output, I went ahead and created a separate issue in https://github.com/openrewrite/rewrite-gradle-plugin/issues/27
