### ISSUE TITLE
Problem of running rewrite tasks because of compiling is failed

### ISSUE THREAD

**Issue by phuoctpl** [openrewrite/rewrite-gradle-plugin#293]
I am using rewrite-gradle-plugin for our gralde project which contains several sub modules.
When running rewrite tasks I got an issue about compiling.
The compileJava task was run before and because I had a breaking change, it failed and the rewrite tasks were not run.
I check the task dependency graph and seems like rewrite tasks depend on compile tasks. 
Is this behavior intentional? 
Because I don't need the compilation tasks run before rewrite tasks, can I change it?

**Comment by shanman190** [comment]
So there are two aspects that I'll touch in here:

* The project must be fully compilable at the beginning of a `rewriteRun` / `rewriteDryRun` cycle. The tasks depend upon the compilation tasks of the project because quite often there are other tasks that trigger code generation within a project, so the easiest way to ensure that that any and all code generation processes occur is to depend upon the compilation steps as OpenRewrite needs for all compiler types to be available in order to perform its steps. Furthermore, the source files within the project must be compilable in order for OpenRewrite to generate its LST model from them (NOTE: OpenRewrite goes through its own internal compilation phase to generate the LST model).

* Gradle does not provide an easy mechanism to remove a task dependency as that is pretty unusual within a Gradle build.

**Comment by shanman190** [comment]
@phuoctpl, I'm going to go ahead and close this issue, but please don't hesitate to reach out if you are having more issues. We have a Slack workspace where you can ask questions and get fast feedback as well.
